title: Fahim Ali
description: Welcome to my Portfolio! Here I''ll be posting my projects and documenting my journey with Cybersecurity.
google_analytics:
theme: jekyll-theme-hacker
url: "https://fahim602.github.io"
include:
  - _projects
